# This file was generated by https://github.com/berberman/arch-hs, please check it manually.
# Maintainer: Your Name <youremail@domain.com>

_hkgname=Lisp
pkgname=haskell-lisp
pkgver=0.1.0.0
pkgrel=1
pkgdesc=""
url="https://github.com/MikeBottiniCS510FunctionalProgramming/Lisp.git"
license=("MIT")
arch=('x86_64')
depends=('ghc-libs' 'haskell-parser-combinators')
makedepends=('ghc')
source=("git+https://github.com/MikeBottiniCS510FunctionalProgramming/Lisp.git")
sha256sums=('SKIP')

build() {
  cd $_hkgname

  runhaskell Setup configure -O --enable-shared --enable-executable-dynamic --disable-library-vanilla \
    --prefix=/usr --docdir=/usr/share/doc/$pkgname --datasubdir=$pkgname --enable-tests \
    --dynlibdir=/usr/lib --libsubdir=\$compiler/site-local/\$pkgid \
    --ghc-option=-optl-Wl\,-z\,relro\,-z\,now \
    --ghc-option='-pie' 

  runhaskell Setup build
}

package() {
  cd $_hkgname
  runhaskell Setup copy --destdir="$pkgdir"
  install -D -m644 LICENSE -t "$pkgdir"/usr/share/licenses/$pkgname/
  rm -f "$pkgdir"/usr/share/doc/$pkgname/LICENSE
}
